Boundaryy/Client

app/choose.jsx, app/guardian/home.jsx, app/guardian/result.jsx, app/guardian/signin.jsx, app/guardian/signup.jsx
=> 🐛 :: choose 보호자 경로 수정

app/guardian/advice.jsx, app/guardian/resolve.jsx
=> 🐛 :: 보호자 세션 경로 지정

app/guardian/advice.jsx, app/guardian/home.jsx, package-lock.json, package.json
=> 🐛 :: 보호자 메인 페이지 수정

app/child/training/cogresult.jsx
=> 🐛 포인트 추가 화면 퍼블리싱

app/guardian/signup.jsx
=> 🎨 레포 이름을 바꾸면 내가 커밋을 어케하

app/child/signin.jsx, app/child/signup.jsx, app/choose.jsx, app/index.jsx, components/Button.jsx, package-lock.json, package.json
=> 💄 로그인 유효성 검사

app/guardian/signin.jsx, app/guardian/signup.jsx
=> 🎨 부모 로그인/회원가입 유효성 검사

app/child/training/situchoose.jsx
#33 과 같습니다.  상황 선택 페이지 디자인 수정했습니다.
=> 💚 아이/상황 선택 페이지 디자인 수정

app/guardian/addsitu.jsx, app/guardian/advice.jsx, app/guardian/resolve.jsx, app/guardian/result.jsx, app/guardian/succesadd.jsx
개요는 이슈 #38 과 같습니다.
- 결과 리스트 페이지 디자인 수정
- 결과 확인 후 홈으로 경로 수정
- 상황 추가 페이지 디자인 반영
- 상황 추가시 알림 페이지 디자인 변경
=> 💚 보호자 디자인 수정

app/guardian/addsitu.jsx
보호자/상황추가에서 추가된 상황을 삭제할 수 있도록 구현했습니다. 
등록된 상황명과 동일하게 삭제를 하면 [~ 상황 삭제] 가 되도록 구현했습니다. 
+ 삭제 버튼 클릭시 팝업창 띄우기
=> ✨ [상황추가] 삭제 버튼 구현

app/child/signin.jsx, app/guardian/signin.jsx
- [로그인] 부모님과 아이의 로그인에 API를 연결했습니다. 보내질 때 
```
{
"userId": "string",
"password": "string"
}
```
이 형식으로 보내집니다.
=> ✨ [로그인] API 연결

app/child/signin.jsx, app/child/signup.jsx, app/guardian/signup.jsx
[회원가입] 보호자/아이 회원가입 API 호출 경로를 수정했습니다.
=> 🐛 [회원가입] API 호출 경로 수정

app/child/home.jsx
=> 💄 [홈] user 정보 API 연결

app/guardian/addsitu.jsx, app/guardian/signin.jsx
=> ✨ [보호자] 상황 API 연결 (조회, 추가, 삭제)

app/guardian/addsitu.jsx
상황 API 모르고 선택적 상황 api를 끌고 와서 전체로 끌고오는 걸로 바꿨습니당.
=> 🐛 상황 API 변경

app/child/training/resolve.jsx
=> ✨ [아이] SST 스레드 생성 api 연결

app/guardian/babysitu.jsx
=> ✨ [보호자]아이 포인트 api 연결

app/child/home.jsx, app/child/signin.jsx, app/child/signup.jsx, app/child/training/point.jsx, app/child/training/resolve.jsx, app/child/training/resultcontent.jsx, app/child/training/situchoose.jsx, app/guardian/addsitu.jsx, app/guardian/babysitu.jsx, app/guardian/resolve.jsx, app/guardian/result.jsx, app/guardian/signin.jsx, app/guardian/signup.jsx
=> 🐛 서버 주소 변경

app/child/signin.jsx, app/child/training/situchoose.jsx, package-lock.json
=> AsyncStorage 데이터 저장 추출 구현

.env
=> FIX :: env 경로 수정

app/guardian/home.jsx
=> 🐛 [보호자 home] CSS 수정
